 type: web
    name: fuvartestbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: <ADD_YOUR_TOKEN_MANUALLY>
      - key: WEBHOOK_URL
        value: <ADD_YOUR_WEBHOOK_URL_MANUALLY>
